name: aina
description: Project for Diploma Work.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # UI
  cupertino_icons: ^1.0.2
  responsive_framework: ^0.2.0
  # window_size:
  #   git:
  #     url: git://github.com/google/flutter-desktop-embedding.git
  #     path: plugins/window_size

  # State Management
  flutter_bloc: ^8.0.1
  provider: ^6.0.3

  # Audio
  audioplayers: ^0.20.1
  audio_video_progress_bar: ^0.10.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic